import './globals.css'
import { Inter, Alegreya } from 'next/font/google'
import Nav from './components/nav'
import Foot from './components/foot'

const inter = Inter({ subsets: ['latin'] })
const alegraya = Alegreya({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alegraya.className}>
        <Nav />
        {children}
        <Foot />
      </body>
    </html>
  )
}
